services:
  server:
    build:
      context: .
      target: final
    env_file:
      - .env
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: igropoisk
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    expose:
      - 5432
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
  elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
      volumes:
        - es-data:/usr/share/elasticsearch/data
      environment:
        - discovery.type=single-node
        - xpack.security.enabled=false
      ports:
        - "9200:9200"

volumes:
  es-data:
  db-data:

